import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { app } from 'electron'
import log from 'electron-log/main'
import {
  parseAbilityTagsDataset,
  parseHeroMeta,
  type AbilityTagsLookup,
} from '@core/domain/ability-tags'

// @DEV-GUIDE: Loads the shipped ability-tags dataset (resources/data/
// ability_tags.json + hero_meta.json, generated by ../ad_data_gather_script/
// build_ability_tags.py) once at startup and exposes the core AbilityTagsLookup
// consumed by the scan processor's needs engine and inert-ability filter.
// Missing or invalid files return undefined — the tags feature is then simply
// off (scan processing behaves exactly as before the dataset existed). Unknown
// tags inside an otherwise valid dataset are dropped and logged, never fatal —
// a newer dataset must not brick an older app.

const logger = log.scope('ability-tags')

export function loadAbilityTags(): AbilityTagsLookup | undefined {
  const base = app.isPackaged
    ? process.resourcesPath
    : join(app.getAppPath(), 'resources')
  let tagsRaw: unknown
  let heroRaw: unknown
  try {
    tagsRaw = JSON.parse(
      readFileSync(join(base, 'data', 'ability_tags.json'), 'utf8'),
    )
    heroRaw = JSON.parse(readFileSync(join(base, 'data', 'hero_meta.json'), 'utf8'))
  } catch (err) {
    logger.info('Ability tags dataset not available — tags feature off', {
      error: err instanceof Error ? err.message : String(err),
    })
    return undefined
  }

  const parsed = parseAbilityTagsDataset(tagsRaw)
  const heroMeta = parseHeroMeta(heroRaw)
  if (parsed === null || heroMeta === null) {
    logger.warn('Ability tags dataset invalid — tags feature off')
    return undefined
  }
  if (parsed.droppedTags.length > 0) {
    logger.warn('Dropped unknown tags from dataset', { tags: parsed.droppedTags })
  }
  logger.info('Ability tags loaded', {
    abilities: parsed.tagsByAbility.size,
    curated: parsed.roleMustByAbility.size,
    heroes: heroMeta.size,
  })

  return {
    getTags: (name) => parsed.tagsByAbility.get(name),
    getRoleMust: (name) => parsed.roleMustByAbility.get(name),
    getHeroAttackType: (heroName) => heroMeta.get(heroName)?.attackType,
    getHeroMeta: (heroName) => heroMeta.get(heroName),
  }
}
