// @DEV-GUIDE: Ability function tags (Position Templates spec, step 4). The
// dataset ships as resources/data/ability_tags.json, generated by
// ../ad_data_gather_script/build_ability_tags.py (dotaconstants mechanical layer
// + Liquipedia CC lists + LLM judgment pass + tag_overrides.json) and curated by
// hand via its review_flags.json. This module owns the CLOSED vocabulary (the
// build script's VOCAB must match) and the pure parsing/validation used by the
// main-process loader. Tags power the build-needs engine and the reason chips —
// role RANKING is primarily the shifts-derived greed axis (role-scoring.ts);
// tags deliberately carry only small static weights to avoid double-counting.

export const TAG_VOCABULARY = [
  'hard_cc',
  'soft_cc',
  'setup_cc',
  'aoe',
  'nuke',
  'waveclear',
  'farm_tool',
  'steroid',
  'sustain_self',
  'save_ally',
  'team_aura',
  'mobility',
  'initiation',
  'summon',
  'teamfight_ult',
  'passive_value',
  'melee_only',
  'ranged_only',
  'mana_hungry',
  'channeled',
] as const

export type AbilityTag = (typeof TAG_VOCABULARY)[number]

const VOCAB_SET: ReadonlySet<string> = new Set(TAG_VOCABULARY)

export type HeroAttackType = 'Melee' | 'Ranged'
export type HeroPrimaryAttr = 'str' | 'agi' | 'int' | 'all'

/** Hero-model metadata (hero_meta.json): attributes for role-fit scoring. */
export interface HeroMeta {
  attackType?: HeroAttackType
  primaryAttr?: HeroPrimaryAttr
  baseStr?: number
  baseAgi?: number
  baseInt?: number
  strGain?: number
  agiGain?: number
  intGain?: number
}

/** Injected into the scan processor; absent dep = tags feature off (no-op). */
export interface AbilityTagsLookup {
  /** Tags for an ability internal name; undefined when untagged/unknown. */
  getTags(abilityName: string): ReadonlySet<AbilityTag> | undefined
  /** Attack type of a hero internal name (hero_meta.json); undefined when unknown. */
  getHeroAttackType(heroName: string): HeroAttackType | undefined
  /** Full hero metadata (attributes/gains) for model role-fit; undefined when unknown. */
  getHeroMeta(heroName: string): HeroMeta | undefined
}

/**
 * Parse + validate the ability_tags.json dataset. Unknown tags are DROPPED
 * (with their names reported) rather than failing the load — a newer dataset
 * must never brick an older app. Returns null for structurally invalid input.
 */
export function parseAbilityTagsDataset(json: unknown): {
  tagsByAbility: Map<string, ReadonlySet<AbilityTag>>
  droppedTags: string[]
} | null {
  if (typeof json !== 'object' || json === null) return null
  const abilities = (json as { abilities?: unknown }).abilities
  if (typeof abilities !== 'object' || abilities === null) return null

  const tagsByAbility = new Map<string, ReadonlySet<AbilityTag>>()
  const dropped = new Set<string>()
  for (const [name, entry] of Object.entries(abilities)) {
    const rawTags = (entry as { tags?: unknown })?.tags
    if (!Array.isArray(rawTags)) continue
    const tags = new Set<AbilityTag>()
    for (const tag of rawTags) {
      if (typeof tag === 'string' && VOCAB_SET.has(tag)) {
        tags.add(tag as AbilityTag)
      } else if (typeof tag === 'string') {
        dropped.add(tag)
      }
    }
    tagsByAbility.set(name, tags)
  }
  return { tagsByAbility, droppedTags: [...dropped] }
}

/** Parse + validate hero_meta.json. Missing/invalid stat fields become
 * undefined (model fit then treats them as neutral) — never fatal. */
export function parseHeroMeta(json: unknown): Map<string, HeroMeta> | null {
  if (typeof json !== 'object' || json === null) return null
  const num = (v: unknown): number | undefined =>
    typeof v === 'number' && Number.isFinite(v) ? v : undefined
  const result = new Map<string, HeroMeta>()
  for (const [name, entry] of Object.entries(json)) {
    if (typeof entry !== 'object' || entry === null) continue
    const e = entry as Record<string, unknown>
    const meta: HeroMeta = {
      attackType:
        e.attackType === 'Melee' || e.attackType === 'Ranged'
          ? e.attackType
          : undefined,
      primaryAttr:
        e.primaryAttr === 'str' ||
        e.primaryAttr === 'agi' ||
        e.primaryAttr === 'int' ||
        e.primaryAttr === 'all'
          ? e.primaryAttr
          : undefined,
      baseStr: num(e.baseStr),
      baseAgi: num(e.baseAgi),
      baseInt: num(e.baseInt),
      strGain: num(e.strGain),
      agiGain: num(e.agiGain),
      intGain: num(e.intGain),
    }
    result.set(name, meta)
  }
  return result
}

/**
 * True when an ability is mechanically inert or crippled on the given hero
 * model's attack type (cleave on a ranged model, projectile mechanics on a
 * melee one). Used as a HARD top-tier exclusion, not a score tweak.
 */
export function isInertOnModel(
  tags: ReadonlySet<AbilityTag> | undefined,
  attackType: HeroAttackType | undefined,
): boolean {
  if (tags === undefined || attackType === undefined) return false
  return (
    (attackType === 'Ranged' && tags.has('melee_only')) ||
    (attackType === 'Melee' && tags.has('ranged_only'))
  )
}
