// @DEV-GUIDE: Ability function tags (Position Templates spec, step 4). The
// dataset ships as resources/data/ability_tags.json, generated by
// ../ad_data_gather_script/build_ability_tags.py (dotaconstants mechanical layer
// + Liquipedia CC lists + LLM judgment pass + tag_overrides.json) and curated by
// hand via its review_flags.json. This module owns the CLOSED vocabulary (the
// build script's VOCAB must match) and the pure parsing/validation used by the
// main-process loader. Tags power the build-needs engine and the reason chips —
// role RANKING is primarily the shifts-derived greed axis (role-scoring.ts);
// tags deliberately carry only small static weights to avoid double-counting.
// Distinct from tags, an entry may carry `roleMust: [positions]` — a hand-
// curated VERDICT (not a mechanical fact, so deliberately outside the tag
// vocabulary): "recommend this for these positions even if stats disagree".
// Reserved for abilities whose value the stats systematically miss (e.g.
// Glimpse for supports); it guarantees a top-tier slot when the user's active
// role matches (top-tier.ts) on top of a role-layer boost (role-scoring.ts).

export const TAG_VOCABULARY = [
  'hard_cc',
  'soft_cc',
  'setup_cc',
  'aoe',
  'nuke',
  'waveclear',
  'farm_tool',
  'steroid',
  'sustain_self',
  'save_ally',
  'team_aura',
  'mobility',
  'initiation',
  'summon',
  'teamfight_ult',
  'passive_value',
  'melee_only',
  'ranged_only',
  'grants_ranged',
  'mana_hungry',
  'channeled',
] as const

export type AbilityTag = (typeof TAG_VOCABULARY)[number]

const VOCAB_SET: ReadonlySet<string> = new Set(TAG_VOCABULARY)

export type HeroAttackType = 'Melee' | 'Ranged'
export type HeroPrimaryAttr = 'str' | 'agi' | 'int' | 'all'

/** Hero-model metadata (hero_meta.json): attributes for role-fit scoring plus
 * chassis fields (model-pairing Layer A) — the body properties stat gains
 * cannot see. All optional: missing data scores as a neutral percentile. */
export interface HeroMeta {
  attackType?: HeroAttackType
  primaryAttr?: HeroPrimaryAttr
  baseStr?: number
  baseAgi?: number
  baseInt?: number
  strGain?: number
  agiGain?: number
  intGain?: number
  attackRange?: number
  /** BAT (base attack time) — LOWER is better. */
  attackRate?: number
  projectileSpeed?: number
  moveSpeed?: number
  baseArmor?: number
  baseHealth?: number
  baseMana?: number
  baseAttackMin?: number
  baseAttackMax?: number
}

/** Draft position (1-5). Structurally identical to role-scoring's
 * DraftPosition — declared here too so this module stays import-free of the
 * scoring layer. */
export type RoleMustPosition = 1 | 2 | 3 | 4 | 5

/** Injected into the scan processor; absent dep = tags feature off (no-op). */
export interface AbilityTagsLookup {
  /** Tags for an ability internal name; undefined when untagged/unknown. */
  getTags(abilityName: string): ReadonlySet<AbilityTag> | undefined
  /** Curated must-pick positions for an ability; undefined when not curated. */
  getRoleMust(abilityName: string): ReadonlySet<RoleMustPosition> | undefined
  /** Dependency gate: entries are ability internal names or 'model:<hero>'.
   * The ability is only ever SUGGESTED when at least one entry is satisfied
   * (Eclipse -> Lucent Beam; Requiem -> the SF model whose innate feeds it). */
  getRequires(abilityName: string): readonly string[] | undefined
  /** Attack type of a hero internal name (hero_meta.json); undefined when unknown. */
  getHeroAttackType(heroName: string): HeroAttackType | undefined
  /** Full hero metadata (attributes/gains) for model role-fit; undefined when unknown. */
  getHeroMeta(heroName: string): HeroMeta | undefined
}

/**
 * Parse + validate the ability_tags.json dataset. Unknown tags are DROPPED
 * (with their names reported) rather than failing the load — a newer dataset
 * must never brick an older app. Returns null for structurally invalid input.
 */
export function parseAbilityTagsDataset(json: unknown): {
  tagsByAbility: Map<string, ReadonlySet<AbilityTag>>
  roleMustByAbility: Map<string, ReadonlySet<RoleMustPosition>>
  requiresByAbility: Map<string, readonly string[]>
  droppedTags: string[]
} | null {
  if (typeof json !== 'object' || json === null) return null
  const abilities = (json as { abilities?: unknown }).abilities
  if (typeof abilities !== 'object' || abilities === null) return null

  const tagsByAbility = new Map<string, ReadonlySet<AbilityTag>>()
  const roleMustByAbility = new Map<string, ReadonlySet<RoleMustPosition>>()
  const requiresByAbility = new Map<string, readonly string[]>()
  const dropped = new Set<string>()
  for (const [name, entry] of Object.entries(abilities)) {
    const rawTags = (entry as { tags?: unknown })?.tags
    if (!Array.isArray(rawTags)) continue
    const tags = new Set<AbilityTag>()
    for (const tag of rawTags) {
      if (typeof tag === 'string' && VOCAB_SET.has(tag)) {
        tags.add(tag as AbilityTag)
      } else if (typeof tag === 'string') {
        dropped.add(tag)
      }
    }
    tagsByAbility.set(name, tags)

    // Curated must-pick positions: invalid values are dropped silently (a
    // newer dataset must never brick an older app), empty sets are omitted.
    const rawMust = (entry as { roleMust?: unknown })?.roleMust
    if (Array.isArray(rawMust)) {
      const positions = new Set<RoleMustPosition>()
      for (const pos of rawMust) {
        if (typeof pos === 'number' && Number.isInteger(pos) && pos >= 1 && pos <= 5) {
          positions.add(pos as RoleMustPosition)
        }
      }
      if (positions.size > 0) roleMustByAbility.set(name, positions)
    }

    // Dependency gates: non-empty strings only, deduped; empty lists omitted.
    const rawRequires = (entry as { requires?: unknown })?.requires
    if (Array.isArray(rawRequires)) {
      const reqs = [
        ...new Set(
          rawRequires.filter((r): r is string => typeof r === 'string' && r.length > 0),
        ),
      ]
      if (reqs.length > 0) requiresByAbility.set(name, reqs)
    }
  }
  return { tagsByAbility, roleMustByAbility, requiresByAbility, droppedTags: [...dropped] }
}

/** Parse + validate hero_meta.json. Missing/invalid stat fields become
 * undefined (model fit then treats them as neutral) — never fatal. */
export function parseHeroMeta(json: unknown): Map<string, HeroMeta> | null {
  if (typeof json !== 'object' || json === null) return null
  const num = (v: unknown): number | undefined =>
    typeof v === 'number' && Number.isFinite(v) ? v : undefined
  const result = new Map<string, HeroMeta>()
  for (const [name, entry] of Object.entries(json)) {
    if (typeof entry !== 'object' || entry === null) continue
    const e = entry as Record<string, unknown>
    const meta: HeroMeta = {
      attackType:
        e.attackType === 'Melee' || e.attackType === 'Ranged'
          ? e.attackType
          : undefined,
      primaryAttr:
        e.primaryAttr === 'str' ||
        e.primaryAttr === 'agi' ||
        e.primaryAttr === 'int' ||
        e.primaryAttr === 'all'
          ? e.primaryAttr
          : undefined,
      baseStr: num(e.baseStr),
      baseAgi: num(e.baseAgi),
      baseInt: num(e.baseInt),
      strGain: num(e.strGain),
      agiGain: num(e.agiGain),
      intGain: num(e.intGain),
      attackRange: num(e.attackRange),
      attackRate: num(e.attackRate),
      projectileSpeed: num(e.projectileSpeed),
      moveSpeed: num(e.moveSpeed),
      baseArmor: num(e.baseArmor),
      baseHealth: num(e.baseHealth),
      baseMana: num(e.baseMana),
      baseAttackMin: num(e.baseAttackMin),
      baseAttackMax: num(e.baseAttackMax),
    }
    result.set(name, meta)
  }
  return result
}

/** Context that can WAIVE the inert filter for a candidate. */
export interface InertExceptions {
  /** The candidate is native to the selected model's hero (Wukong's Command on
   * the Monkey King model): the game designed them together — never inert. */
  nativeToModel?: boolean
  /** One of the user's DRAFTED abilities is tagged grants_ranged (Psi Blades,
   * Take Aim): ranged_only candidates work on a melee model again. */
  picksGrantRanged?: boolean
}

/**
 * True when an ability is mechanically inert or crippled on the given hero
 * model's attack type (cleave on a ranged model, projectile mechanics on a
 * melee one). Used as a HARD top-tier exclusion, not a score tweak.
 * Exceptions (user ruling 2026-08-30, Wukong's Command case): the candidate's
 * own native model is always exempt, and a drafted grants_ranged ability
 * waives ranged_only on melee models (melee_only on ranged models has no
 * symmetric waiver — nothing grants melee).
 */
export function isInertOnModel(
  tags: ReadonlySet<AbilityTag> | undefined,
  attackType: HeroAttackType | undefined,
  exceptions?: InertExceptions,
): boolean {
  if (tags === undefined || attackType === undefined) return false
  if (exceptions?.nativeToModel === true) return false
  if (attackType === 'Ranged' && tags.has('melee_only')) return true
  if (attackType === 'Melee' && tags.has('ranged_only')) {
    return exceptions?.picksGrantRanged !== true
  }
  return false
}
